[package]
name = "gameboy_emu"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
winit = "0.29.15"
softbuffer = "0.4.6"
smallvec = "1.14.0"
cpal = "0.15.3"

[profile.release]
debug = true
